# .github/workflows/sign.yml
name: Build & Sign Firefox Add-on

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sign extension
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: "./"
          artifacts: "signed"
          channel: "unlisted"
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: Upload signed XPI
        uses: actions/upload-artifact@v4
        with:
          name: firefox-xpi
          path: signed/*.xpi
